// server/config/reset.js
import { pool } from './database.js';
import './dotenv.js';

const resetDatabase = async () => {
  try {
    // Drop existing tables
    await pool.query(`
      DROP TABLE IF EXISTS saved_dates CASCADE;
      DROP TABLE IF EXISTS comments CASCADE;
      DROP TABLE IF EXISTS likes CASCADE;
      DROP TABLE IF EXISTS date_ideas CASCADE;
      DROP TABLE IF EXISTS users CASCADE;
    `);
    console.log('🗑️  Tables dropped successfully');

    // Create users table
    await pool.query(`
      CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        username VARCHAR(255) NOT NULL UNIQUE,
        email VARCHAR(255) NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log('🎉 users table created successfully');

    // Create date_ideas table with updated schema
    await pool.query(`
      CREATE TABLE date_ideas (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description TEXT,
        location VARCHAR(100),
        cost_category VARCHAR(50),
        duration VARCHAR(50),
        activity_type VARCHAR(50),
        mood VARCHAR(50),
        time_of_day VARCHAR(50),
        distance VARCHAR(50),
        importance VARCHAR(50),
        activity_level VARCHAR(50),
        image_url VARCHAR(255),
        is_shared BOOLEAN DEFAULT FALSE,
        creator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log('🎉 date_ideas table created successfully');

    // Create likes table
    await pool.query(`
      CREATE TABLE likes (
        id SERIAL PRIMARY KEY,
        date_idea_id INTEGER REFERENCES date_ideas(id) ON DELETE CASCADE,
        user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(user_id, date_idea_id)
      );
    `);
    console.log('🎉 likes table created successfully');

    // Create comments table with user reference
    await pool.query(`
      CREATE TABLE comments (
        id SERIAL PRIMARY KEY,
        date_idea_id INTEGER REFERENCES date_ideas(id) ON DELETE CASCADE,
        user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
        content TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    console.log('🎉 comments table created successfully');

    // Create saved_dates table
    await pool.query(`
      CREATE TABLE saved_dates (
        id SERIAL PRIMARY KEY,
        user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
        date_idea_id INTEGER REFERENCES date_ideas(id) ON DELETE CASCADE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(user_id, date_idea_id)
      );
    `);
    console.log('🎉 saved_dates table created successfully');

    // Insert sample date ideas
    const sampleDateIdeas = [
      // Your existing sample date ideas array...
      {
        title: 'Sunrise Hike',
        description: 'Begin your day with an invigorating hike to watch the sunrise from the mountaintop.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'hiking',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 2
      {
        title: 'Luxury Spa Evening',
        description: 'Relax and rejuvenate with a premium spa experience, complete with massages and aromatherapy.',
        location: 'indoor',
        cost_category: 'luxury',
        duration: '3-4 hours',
        activity_type: 'spa',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 3
      {
        title: 'Romantic Dinner Cruise',
        description: 'Enjoy a candlelit dinner on a boat while cruising under the stars.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'boatRide',
        mood: 'romantic',
        time_of_day: 'night',
        distance: 'local',
        importance: 'connection',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 4
      {
        title: 'Artisan Cooking Class',
        description: 'Learn to cook gourmet dishes together with a professional chef.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '3 hours',
        activity_type: 'cooking',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 5
      {
        title: 'Stargazing Picnic',
        description: 'Set up a cozy picnic and gaze at the stars with a telescope and constellation guide.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'stargazing',
        mood: 'romantic',
        time_of_day: 'night',
        distance: 'nearby',
        importance: 'connection',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 6
      {
        title: 'Local Coffee Shop Tour',
        description: 'Explore the best coffee shops in town and enjoy different brews.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2 hours',
        activity_type: 'coffeeTour',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 7
      {
        title: 'Museum Art Exploration',
        description: 'Visit an art museum and immerse yourselves in creative masterpieces.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '3 hours',
        activity_type: 'museum',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 8
      {
        title: 'Beach Sunset Walk',
        description: 'Take a leisurely walk along the beach and watch the sunset together.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'beachWalk',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'nearby',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 9
      {
        title: 'Surprise Mystery Trip',
        description: 'Embark on a spontaneous trip to an unknown destination for an element of surprise.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: 'Full day',
        activity_type: 'mysteryTrip',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'surprise',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 10
      {
        title: 'Skydiving Adventure',
        description: 'Feel the adrenaline rush with a tandem skydive over stunning landscapes.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: 'Full day',
        activity_type: 'skydiving',
        mood: 'adventurous',
        time_of_day: 'afternoon',
        distance: 'far',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 11
      {
        title: 'Pottery Workshop',
        description: 'Get creative together at a hands-on pottery class.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'pottery',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 12
      {
        title: 'Wine Tasting Tour',
        description: 'Visit local vineyards and enjoy a variety of wines.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '4+ hours',
        activity_type: 'wineTasting',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 13
      {
        title: 'Karaoke Night',
        description: 'Sing your hearts out at a lively karaoke bar.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'karaoke',
        mood: 'creative',
        time_of_day: 'night',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 14
      {
        title: 'Escape Room Challenge',
        description: 'Work together to solve puzzles and escape within the time limit.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'escapeRoom',
        mood: 'adventurous',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 15
      {
        title: 'Bike Ride Through the Park',
        description: 'Enjoy a leisurely bike ride through scenic paths.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'biking',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 16
      {
        title: 'Hot Air Balloon Ride',
        description: 'Soar above the landscape in a hot air balloon.',
        location: 'outdoor',
        cost_category: 'luxury',
        duration: '2-3 hours',
        activity_type: 'balloonRide',
        mood: 'romantic',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 17
      {
        title: 'Attend a Live Concert',
        description: 'Enjoy live music from your favorite artists.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '3-4 hours',
        activity_type: 'concert',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 18
      {
        title: 'Couples Yoga Session',
        description: 'Enhance your connection with a guided couples yoga class.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'yoga',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 19
      {
        title: 'Visit a Botanical Garden',
        description: 'Stroll through beautiful gardens and admire the flora.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'gardenVisit',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 20
      {
        title: 'Movie Marathon at Home',
        description: 'Cozy up at home with a selection of your favorite movies.',
        location: 'indoor',
        cost_category: 'free',
        duration: '4+ hours',
        activity_type: 'movieNight',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 21
      {
        title: 'Picnic in the Park',
        description: 'Pack a basket and enjoy a picnic in a picturesque park.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'picnic',
        mood: 'romantic',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'connection',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 22
      {
        title: 'Go to a Comedy Show',
        description: 'Laugh together at a stand-up comedy performance.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'comedyShow',
        mood: 'creative',
        time_of_day: 'night',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 23
      {
        title: 'Painting and Wine Night',
        description: 'Enjoy a guided painting session while sipping on wine.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'painting',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 24
      {
        title: 'Visit a Science Museum',
        description: 'Explore interactive exhibits at the science museum.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '3-4 hours',
        activity_type: 'scienceMuseum',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 25
      {
        title: 'Salsa Dancing Class',
        description: 'Learn some new moves at a salsa dancing class.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'dancing',
        mood: 'romantic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 26
      {
        title: 'Bookstore Date',
        description: 'Browse books together and share your favorite reads.',
        location: 'indoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'bookstore',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'connection',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 27
      {
        title: 'Attend a Sports Game',
        description: 'Cheer on your favorite team at a live sports event.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '3-4 hours',
        activity_type: 'sportsGame',
        mood: 'adventurous',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 28
      {
        title: 'Indoor Rock Climbing',
        description: 'Challenge yourselves at an indoor rock climbing gym.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'rockClimbing',
        mood: 'adventurous',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 29
      {
        title: 'Volunteer Together',
        description: 'Give back to the community by volunteering together.',
        location: 'varies',
        cost_category: 'free',
        duration: '3-4 hours',
        activity_type: 'volunteering',
        mood: 'romantic',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 30
      {
        title: 'Photography Walk',
        description: 'Explore the city and capture moments with photography.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'photography',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 31
      {
        title: 'Amusement Park Adventure',
        description: 'Have fun on rides and games at the amusement park.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: 'Full day',
        activity_type: 'amusementPark',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 32
      {
        title: 'Cooking Dinner Together at Home',
        description: 'Prepare a meal together in the comfort of your home.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'cooking',
        mood: 'romantic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'connection',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 33
      {
        title: 'Visit a Farmers Market',
        description: 'Browse fresh produce and artisan goods at the market.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'farmersMarket',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 34
      {
        title: 'Go Kayaking or Canoeing',
        description: 'Enjoy the water with a kayaking or canoeing trip.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'kayaking',
        mood: 'adventurous',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 35
      {
        title: 'Take a Language Class',
        description: 'Learn a new language together in a fun environment.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'languageClass',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 36
      {
        title: 'Attend a Poetry Reading',
        description: 'Enjoy spoken word performances at a local venue.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'poetry',
        mood: 'creative',
        time_of_day: 'night',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 37
      {
        title: 'Meditation Retreat',
        description: 'Find peace and relaxation at a guided meditation session.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '3-4 hours',
        activity_type: 'meditation',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 38
      {
        title: 'Road Trip to a Nearby Town',
        description: 'Explore a new place with a spontaneous road trip.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: 'Full day',
        activity_type: 'roadTrip',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 39
      {
        title: 'Camping Under the Stars',
        description: 'Spend a night outdoors camping and stargazing.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: 'Overnight',
        activity_type: 'camping',
        mood: 'romantic',
        time_of_day: 'night',
        distance: 'nearby',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 40
      {
        title: 'Visit an Aquarium',
        description: 'Discover marine life at a local aquarium.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'aquarium',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 41
      {
        title: 'Chocolate Factory Tour',
        description: 'Indulge your sweet tooth with a chocolate factory tour.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'factoryTour',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 42
      {
        title: 'Ghost Tour of the City',
        description: 'Explore haunted sites on a guided ghost tour.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'ghostTour',
        mood: 'adventurous',
        time_of_day: 'night',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 43
      {
        title: 'Stand-Up Paddleboarding',
        description: 'Try out stand-up paddleboarding on calm waters.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'paddleboarding',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 44
      {
        title: 'Attend a Theater Play',
        description: 'Enjoy a live performance at the theater.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'theater',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 45
      {
        title: 'Visit a Planetarium',
        description: 'Explore the cosmos at the planetarium.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'planetarium',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 46
      {
        title: 'Horseback Riding',
        description: 'Enjoy a scenic ride on horseback.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'horsebackRiding',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 47
      {
        title: 'Explore a Historical Site',
        description: 'Visit a local historical landmark and learn its history.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'historicalSite',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 48
      {
        title: 'Go Bowling',
        description: 'Have fun competing in a game of bowling.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'bowling',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 49
      {
        title: 'Visit a Zoo',
        description: 'See animals from around the world at the zoo.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '3-4 hours',
        activity_type: 'zoo',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 50
      {
        title: 'Mini Golf Date',
        description: 'Enjoy a playful round of mini golf.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'miniGolf',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 51
      {
        title: 'Ice Skating',
        description: 'Glide together on the ice at a local rink.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'iceSkating',
        mood: 'romantic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 52
      {
        title: 'Attend a Food Festival',
        description: 'Taste a variety of foods at a local festival.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '3-4 hours',
        activity_type: 'foodFestival',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 53
      {
        title: 'Glass Blowing Class',
        description: 'Create your own glass art pieces.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'glassBlowing',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 54
      {
        title: 'Go-Kart Racing',
        description: 'Race each other on a go-kart track.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'goKarting',
        mood: 'adventurous',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 55
      {
        title: 'Attend a Workshop',
        description: 'Learn a new skill at a local workshop.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'workshop',
        mood: 'creative',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 56
      {
        title: 'Visit an Escape Game',
        description: 'Challenge yourselves in a themed escape game.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'escapeGame',
        mood: 'adventurous',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'surprise',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 57
      {
        title: 'Laser Tag',
        description: 'Engage in a fun game of laser tag.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'laserTag',
        mood: 'adventurous',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 58
      {
        title: 'Visit a Theme Park',
        description: 'Enjoy rides and attractions at a theme park.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: 'Full day',
        activity_type: 'themePark',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 59
      {
        title: 'Attend a Music Festival',
        description: 'Immerse yourselves in live music at a festival.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: 'Full day',
        activity_type: 'musicFestival',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'far',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 60
      {
        title: 'Visit a Hot Spring',
        description: 'Relax in the natural warmth of hot springs.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '3-4 hours',
        activity_type: 'hotSpring',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 61
      {
        title: 'Visit an Art Gallery Opening',
        description: 'Attend an art gallery opening and meet the artists.',
        location: 'indoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'artGallery',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 62
      {
        title: 'Attend a Cooking Demonstration',
        description: 'Watch professional chefs cook and learn new recipes.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'cookingDemo',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 63
      {
        title: 'Visit a Brewery or Distillery',
        description: 'Tour a brewery or distillery and sample their products.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'breweryTour',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 64
      {
        title: 'Watch a Sunrise at the Beach',
        description: 'Enjoy the tranquility of a beach sunrise.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'beachSunrise',
        mood: 'romantic',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'connection',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 65
      {
        title: 'Take a Dance Class Together',
        description: 'Learn a new dance style as a couple.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'danceClass',
        mood: 'romantic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 66
      {
        title: 'Visit a Local Fair',
        description: 'Enjoy rides, games, and food at a local fair.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '3-4 hours',
        activity_type: 'localFair',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 67
      {
        title: 'Attend a Meditation Class',
        description: 'Find inner peace at a guided meditation session.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'meditationClass',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 68
      {
        title: 'Go Snowboarding or Skiing',
        description: 'Hit the slopes for some winter sports fun.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: 'Full day',
        activity_type: 'snowSports',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 69
      {
        title: 'Take a Pottery Painting Class',
        description: 'Paint your own pottery pieces together.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'potteryPainting',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 70
      {
        title: 'Visit a Cat Café or Animal Shelter',
        description: 'Spend time with adorable animals.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'animalVisit',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 71
      {
        title: 'Have a Game Night at Home',
        description: 'Enjoy board games or video games together.',
        location: 'indoor',
        cost_category: 'free',
        duration: '4+ hours',
        activity_type: 'gameNight',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 72
      {
        title: 'Visit a Flower Festival',
        description: 'Admire the beauty of flowers at a local festival.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'flowerFestival',
        mood: 'romantic',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 73
      {
        title: 'Take a Helicopter Tour',
        description: 'See the city from above on a helicopter ride.',
        location: 'outdoor',
        cost_category: 'luxury',
        duration: '1-2 hours',
        activity_type: 'helicopterTour',
        mood: 'adventurous',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 74
      {
        title: 'Attend a Book Reading',
        description: 'Listen to authors read from their latest works.',
        location: 'indoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'bookReading',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 75
      {
        title: 'Go Fruit Picking at a Farm',
        description: 'Pick fresh fruits together at a local farm.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'fruitPicking',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      }, {
        title: 'Zip Lining Adventure',
        description: 'Experience the thrill of zip lining through lush forests.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'zipLining',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 77
      {
        title: 'Wine and Paint Night',
        description: 'Unleash your creativity with a guided painting session and wine tasting.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '3 hours',
        activity_type: 'painting',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 78
      {
        title: 'Bird Watching Expedition',
        description: 'Explore nature trails and observe local bird species.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'birdWatching',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'relaxation',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 79
      {
        title: 'Couples Massage Workshop',
        description: 'Learn massage techniques to help each other relax.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2 hours',
        activity_type: 'massageWorkshop',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'bonding',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 80
      {
        title: 'Hot Air Balloon Ride',
        description: 'Soar above the landscape in a hot air balloon for breathtaking views.',
        location: 'outdoor',
        cost_category: 'luxury',
        duration: '1-2 hours',
        activity_type: 'balloonRide',
        mood: 'romantic',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 81
      {
        title: 'Live Jazz Concert',
        description: 'Enjoy smooth jazz tunes at a cozy local venue.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '3 hours',
        activity_type: 'concert',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 82
      {
        title: 'Nature Photography Walk',
        description: 'Capture stunning natural scenes on a guided photography walk.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '3 hours',
        activity_type: 'photography',
        mood: 'curious',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'exploration',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 83
      {
        title: 'Cooking Dinner Together at Home',
        description: 'Prepare a gourmet meal together in the comfort of your kitchen.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '3-4 hours',
        activity_type: 'cooking',
        mood: 'romantic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'connection',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 84
      {
        title: 'Attend a Stand-Up Comedy Show',
        description: 'Laugh together at a lively stand-up comedy performance.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'comedyShow',
        mood: 'playful',
        time_of_day: 'night',
        distance: 'local',
        importance: 'fun',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 85
      {
        title: 'Botanical Garden Tour',
        description: 'Stroll through beautiful gardens and admire diverse plant species.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'gardenVisit',
        mood: 'serene',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'relaxation',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 86
      {
        title: 'Karaoke Night',
        description: 'Sing your favorite songs at a vibrant karaoke bar.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'karaoke',
        mood: 'playful',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'fun',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 87
      {
        title: 'Escape Room Challenge',
        description: 'Solve puzzles together to escape within the time limit.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'escapeRoom',
        mood: 'adventurous',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 88
      {
        title: 'Indoor Rock Climbing',
        description: 'Challenge yourselves at an indoor rock climbing gym.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'rockClimbing',
        mood: 'adventurous',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 89
      {
        title: 'Attend a Cooking Workshop',
        description: 'Learn to cook new dishes with a professional chef.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '3 hours',
        activity_type: 'cookingWorkshop',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'learning',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 90
      {
        title: 'Hot Springs Relaxation',
        description: 'Soak in natural hot springs for ultimate relaxation.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '3-4 hours',
        activity_type: 'hotSprings',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'relaxation',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 91
      {
        title: 'Attend a Science Lecture',
        description: 'Engage in an enlightening lecture on a scientific topic.',
        location: 'indoor',
        cost_category: 'free',
        duration: '2 hours',
        activity_type: 'lecture',
        mood: 'curious',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 92
      {
        title: 'Couples Yoga Session',
        description: 'Enhance your connection with a guided couples yoga class.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'yoga',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 93
      {
        title: 'Visit a Local Winery',
        description: 'Tour a local winery and sample a variety of wines.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '3 hours',
        activity_type: 'wineTasting',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 94
      {
        title: 'Attend a Magic Show',
        description: 'Be amazed by illusions and magic tricks at a live show.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'magicShow',
        mood: 'playful',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'fun',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 95
      {
        title: 'Explore a Farmers Market',
        description: 'Browse fresh produce and artisanal goods at the farmers market.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'farmersMarket',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 96
      {
        title: 'Trampoline Park Fun',
        description: 'Jump and play at a local trampoline park.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'trampolinePark',
        mood: 'playful',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'fun',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 97
      {
        title: 'Attend a Local Theater Production',
        description: 'Enjoy a live theater performance at a community theater.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'theater',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 98
      {
        title: 'Gardening Workshop',
        description: 'Learn gardening tips and plant your own herbs or flowers.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2 hours',
        activity_type: 'gardening',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 99
      {
        title: 'Attend a Film Screening',
        description: 'Watch a special film screening at a local cinema.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'filmScreening',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'entertainment',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 100
      {
        title: 'Couples Pottery Class',
        description: 'Create pottery pieces together in a hands-on class.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'pottery',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 101
      {
        title: 'Visit a Butterfly Conservatory',
        description: 'Walk among beautiful butterflies in a serene conservatory.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'butterflyConservatory',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'relaxation',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 102
      {
        title: 'Attend a Poetry Slam',
        description: 'Experience powerful spoken word performances at a poetry slam.',
        location: 'indoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'poetrySlam',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 103
      {
        title: 'Rock Concert',
        description: 'Feel the energy of a live rock concert with your favorite band.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '3-4 hours',
        activity_type: 'rockConcert',
        mood: 'energetic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'entertainment',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 104
      {
        title: 'Cooking at a Culinary School',
        description: 'Take a hands-on cooking class at a renowned culinary school.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '3-4 hours',
        activity_type: 'culinaryClass',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'learning',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 105
      {
        title: 'Attend a Live Podcast Recording',
        description: 'Be part of a live audience for your favorite podcast.',
        location: 'indoor',
        cost_category: 'free',
        duration: '2 hours',
        activity_type: 'podcastLive',
        mood: 'curious',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 106
      {
        title: 'Participate in a Trivia Night',
        description: 'Test your knowledge and compete in a fun trivia contest.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'triviaNight',
        mood: 'playful',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'fun',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 107
      {
        title: 'Visit a Virtual Reality Arcade',
        description: 'Experience immersive virtual reality games and adventures.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'vrArcade',
        mood: 'adventurous',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 108
      {
        title: 'Attend a Dance Performance',
        description: 'Watch a captivating dance performance at a local theater.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'dancePerformance',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'entertainment',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 109
      {
        title: 'Go Horseback Riding',
        description: 'Enjoy a scenic horseback ride through trails and nature.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'horsebackRiding',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 110
      {
        title: 'Attend a Tech Expo',
        description: 'Explore the latest in technology and innovations at a tech expo.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '4+ hours',
        activity_type: 'techExpo',
        mood: 'curious',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 111
      {
        title: 'Wine and Cheese Tasting',
        description: 'Savor a selection of wines paired with gourmet cheeses.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2 hours',
        activity_type: 'wineCheeseTasting',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'nearby',
        importance: 'relaxation',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 112
      {
        title: 'Attend a Local Parade',
        description: 'Join the festivities and enjoy the vibrant sights and sounds of a local parade.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '3 hours',
        activity_type: 'parade',
        mood: 'playful',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'fun',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 113
      {
        title: 'Take a Glassmaking Class',
        description: 'Create beautiful glass art pieces in a hands-on class.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '3 hours',
        activity_type: 'glassMaking',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 114
      {
        title: 'Attend a Literary Festival',
        description: 'Celebrate literature with author talks, book signings, and more.',
        location: 'indoor',
        cost_category: 'free',
        duration: 'Full day',
        activity_type: 'literaryFestival',
        mood: 'curious',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 115
      {
        title: 'Beach Volleyball Game',
        description: 'Have a fun game of beach volleyball under the sun.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'beachVolleyball',
        mood: 'energetic',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'fun',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 116
      {
        title: 'Attend a Local Workshop',
        description: 'Participate in a workshop to learn a new skill or hobby.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'workshop',
        mood: 'curious',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'learning',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 117
      {
        title: 'Outdoor Picnic and Games',
        description: 'Enjoy a picnic outdoors with fun games and activities.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '3-4 hours',
        activity_type: 'picnic',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 118
      {
        title: 'Attend a Fashion Show',
        description: 'Watch the latest fashion trends at a local fashion show.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'fashionShow',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'far',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 119
      {
        title: 'Go Snorkeling',
        description: 'Explore underwater life with a snorkeling adventure.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'snorkeling',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 120
      {
        title: 'Attend a Cooking Competition',
        description: 'Watch talented chefs compete in a thrilling cooking competition.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'cookingCompetition',
        mood: 'energetic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'entertainment',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 121
      {
        title: 'Visit a Lighthouse',
        description: 'Explore a historic lighthouse and enjoy panoramic views.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'lighthouseVisit',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'exploration',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 122
      {
        title: 'Attend a Drum Circle',
        description: 'Join a lively drum circle and feel the rhythm.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'drumCircle',
        mood: 'playful',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'fun',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 123
      {
        title: 'Explore an Aquarium',
        description: 'Discover marine life at a large public aquarium.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'aquarium',
        mood: 'curious',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 124
      {
        title: 'Take a Dance Class',
        description: 'Learn a new dance style together in a fun environment.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'danceClass',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 125
      {
        title: 'Attend a Book Club Meeting',
        description: 'Discuss your favorite books and meet new people at a book club.',
        location: 'indoor',
        cost_category: 'free',
        duration: '2 hours',
        activity_type: 'bookClub',
        mood: 'curious',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },// 126
      {
        title: 'Attend a Ceramic Sculpture Workshop',
        description: 'Create unique ceramic sculptures with guidance from an expert.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '3 hours',
        activity_type: 'ceramicSculpture',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 127
      {
        title: 'Participate in a Community Cleanup',
        description: 'Give back to the environment by participating in a local cleanup event.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'communityCleanup',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 128
      {
        title: 'Attend a Stand-Up Paddleboarding Class',
        description: 'Learn the basics of stand-up paddleboarding in a supportive environment.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '2 hours',
        activity_type: 'paddleboardingClass',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'learning',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 129
      {
        title: 'Visit a Local Observatory',
        description: 'Gaze at the stars and learn about constellations at a local observatory.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'observatoryVisit',
        mood: 'curious',
        time_of_day: 'night',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 130
      {
        title: 'Attend a Robotics Workshop',
        description: 'Build and program robots together in a hands-on workshop.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '3-4 hours',
        activity_type: 'roboticsWorkshop',
        mood: 'curious',
        time_of_day: 'afternoon',
        distance: 'far',
        importance: 'learning',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 131
      {
        title: 'Go on a Brewery Tour',
        description: 'Explore local breweries and taste a variety of craft beers.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'breweryTour',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 132
      {
        title: 'Attend a Virtual Reality Gaming Session',
        description: 'Dive into immersive virtual worlds with VR gaming.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'vrGaming',
        mood: 'adventurous',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 133
      {
        title: 'Take a Pottery Wheel Class',
        description: 'Learn to shape clay on the pottery wheel with professional guidance.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'potteryWheel',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 134
      {
        title: 'Attend a Local Art Fair',
        description: 'Browse and purchase unique artworks at a vibrant local art fair.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '3-4 hours',
        activity_type: 'artFair',
        mood: 'creative',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 135
      {
        title: 'Join a Guided Nature Walk',
        description: 'Learn about local flora and fauna on a guided nature walk.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'natureWalk',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'learning',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 136
      {
        title: 'Attend a Wine and Cheese Pairing Event',
        description: 'Discover the perfect wine and cheese combinations at a tasting event.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2 hours',
        activity_type: 'wineCheesePairing',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 137
      {
        title: 'Take a Salsa Dancing Class',
        description: 'Learn the lively moves of salsa dancing in a fun class.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'salsaDancing',
        mood: 'playful',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 138
      {
        title: 'Attend a Local Farmers Market',
        description: 'Shop for fresh produce and handmade goods at the farmers market.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'farmersMarket',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'comfort',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 139
      {
        title: 'Visit a Historical Museum',
        description: 'Explore exhibits that showcase the rich history of your area.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'historicalMuseum',
        mood: 'curious',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 140
      {
        title: 'Attend a Jazz Workshop',
        description: 'Learn to play jazz instruments or understand jazz music better.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'jazzWorkshop',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 141
      {
        title: 'Go on a Scenic Train Ride',
        description: 'Enjoy picturesque landscapes from the comfort of a scenic train ride.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '4-5 hours',
        activity_type: 'trainRide',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 142
      {
        title: 'Attend a Digital Art Exhibition',
        description: 'Experience cutting-edge digital artworks at a local exhibition.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'digitalArtExhibition',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 143
      {
        title: 'Participate in a Charity Run',
        description: 'Join a charity run to support a good cause while staying active.',
        location: 'outdoor',
        cost_category: 'free',
        duration: '3-4 hours',
        activity_type: 'charityRun',
        mood: 'energetic',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'givingBack',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 144
      {
        title: 'Attend a Live Podcast Recording',
        description: 'Be part of the live audience for your favorite podcast.',
        location: 'indoor',
        cost_category: 'free',
        duration: '2 hours',
        activity_type: 'podcastLive',
        mood: 'curious',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 145
      {
        title: 'Join a Book Signing Event',
        description: 'Meet authors and get your favorite books signed.',
        location: 'indoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'bookSigning',
        mood: 'curious',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 146
      {
        title: 'Attend a Local Fashion Show',
        description: 'Witness the latest fashion trends at a local runway show.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'fashionShow',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 147
      {
        title: 'Go Paddleboarding at Sunset',
        description: 'Enjoy a serene paddleboarding session as the sun sets.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '2 hours',
        activity_type: 'paddleboarding',
        mood: 'romantic',
        time_of_day: 'evening',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 148
      {
        title: 'Attend a Robotics Competition',
        description: 'Watch teams compete in building and programming robots.',
        location: 'indoor',
        cost_category: 'free',
        duration: '3 hours',
        activity_type: 'roboticsCompetition',
        mood: 'curious',
        time_of_day: 'afternoon',
        distance: 'far',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 149
      {
        title: 'Take a Glassblowing Class',
        description: 'Create your own glass art pieces in a hands-on class.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'glassBlowing',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 150
      {
        title: 'Attend a Salsa Dancing Showcase',
        description: 'Watch skilled dancers perform exhilarating salsa routines.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'danceShowcase',
        mood: 'playful',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'entertainment',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 151
      {
        title: 'Take a Ceramic Painting Class',
        description: 'Decorate ceramic pieces with your favorite colors and designs.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2 hours',
        activity_type: 'ceramicPainting',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 152
      {
        title: 'Attend a Local Meetup Group',
        description: 'Join a meetup group that shares your interests for a social evening.',
        location: 'indoor',
        cost_category: 'free',
        duration: '3 hours',
        activity_type: 'meetupGroup',
        mood: 'playful',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'connection',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 153
      {
        title: 'Go Ice Fishing',
        description: 'Experience the tranquility of ice fishing on a frozen lake.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '3-4 hours',
        activity_type: 'iceFishing',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 154
      {
        title: 'Attend a Local Charity Gala',
        description: 'Support a good cause by attending a glamorous charity gala.',
        location: 'indoor',
        cost_category: 'luxury',
        duration: '4 hours',
        activity_type: 'charityGala',
        mood: 'romantic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'givingBack',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 155
      {
        title: 'Take a Guided Meditation Session',
        description: 'Find inner peace with a guided meditation class.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '1-2 hours',
        activity_type: 'meditation',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'relaxation',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 156
      {
        title: 'Attend a Virtual Reality Escape Room',
        description: 'Solve puzzles in an immersive virtual reality escape room.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '2 hours',
        activity_type: 'vrEscapeRoom',
        mood: 'adventurous',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 157
      {
        title: 'Join a Local Sports League',
        description: 'Participate in a local sports league for a fun and active date.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: 'Full day',
        activity_type: 'sportsLeague',
        mood: 'energetic',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'fun',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 158
      {
        title: 'Attend a Storytelling Event',
        description: 'Listen to captivating stories shared by local storytellers.',
        location: 'indoor',
        cost_category: 'free',
        duration: '2 hours',
        activity_type: 'storytelling',
        mood: 'curious',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 159
      {
        title: 'Go Horseback Riding on the Beach',
        description: 'Ride horses along the shoreline for a unique experience.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'beachHorsebackRiding',
        mood: 'romantic',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 160
      {
        title: 'Attend a Virtual Concert',
        description: 'Enjoy live music performances from the comfort of your home.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'virtualConcert',
        mood: 'relaxed',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'entertainment',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 161
      {
        title: 'Take a Surfing Lesson',
        description: 'Learn the basics of surfing with a professional instructor.',
        location: 'outdoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'surfingLesson',
        mood: 'energetic',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'learning',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      },
      // 162
      {
        title: 'Attend a Stand-Up Paddleboard Yoga Class',
        description: 'Combine yoga and paddleboarding for a unique fitness experience.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '1-2 hours',
        activity_type: 'paddleboardYoga',
        mood: 'relaxed',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'wellness',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 163
      {
        title: 'Visit a Local Brewery for a Tour and Tasting',
        description: 'Explore the brewing process and taste various craft beers.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'breweryTour',
        mood: 'relaxed',
        time_of_day: 'afternoon',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 164
      {
        title: 'Attend a Local History Lecture',
        description: 'Gain insights into the local history through an engaging lecture.',
        location: 'indoor',
        cost_category: 'free',
        duration: '1-2 hours',
        activity_type: 'historyLecture',
        mood: 'curious',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 165
      {
        title: 'Take a Salsa Dance Class',
        description: 'Learn the energetic moves of salsa dancing together.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '1-2 hours',
        activity_type: 'salsaDance',
        mood: 'playful',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'connection',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 166
      {
        title: 'Go on a Guided Historical Walking Tour',
        description: 'Explore historical landmarks with a knowledgeable guide.',
        location: 'outdoor',
        cost_category: 'economy',
        duration: '2-3 hours',
        activity_type: 'historicalWalkingTour',
        mood: 'curious',
        time_of_day: 'morning',
        distance: 'local',
        importance: 'learning',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 167
      {
        title: 'Attend a Stand-Up Comedy Workshop',
        description: 'Learn the art of comedy and try out your own jokes.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'comedyWorkshop',
        mood: 'playful',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 168
      {
        title: 'Visit a Local Aquarium for a Behind-the-Scenes Tour',
        description: 'Get an exclusive look at the operations of a local aquarium.',
        location: 'indoor',
        cost_category: 'premium',
        duration: '3 hours',
        activity_type: 'aquariumTour',
        mood: 'curious',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 169
      {
        title: 'Attend a Live Theater Performance',
        description: 'Enjoy a captivating live performance at a local theater.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'theaterPerformance',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'entertainment',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 170
      {
        title: 'Join a Local Art Class',
        description: 'Enhance your artistic skills by joining a local art class.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '2-3 hours',
        activity_type: 'artClass',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'learning',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 171
      {
        title: 'Go Horseback Riding at Sunrise',
        description: 'Start your day with a peaceful horseback ride as the sun rises.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: '2-3 hours',
        activity_type: 'sunriseHorsebackRiding',
        mood: 'serene',
        time_of_day: 'morning',
        distance: 'nearby',
        importance: 'experience',
        activity_level: 'moderate',
        image_url: '/api/placeholder/400/300',
      },
      // 172
      {
        title: 'Attend a Live Band Performance',
        description: 'Enjoy live music from local bands at a popular venue.',
        location: 'indoor',
        cost_category: 'standard',
        duration: '3 hours',
        activity_type: 'liveBand',
        mood: 'energetic',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'entertainment',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 173
      {
        title: 'Take a DIY Craft Workshop',
        description: 'Create personalized crafts together in a fun workshop.',
        location: 'indoor',
        cost_category: 'economy',
        duration: '2 hours',
        activity_type: 'craftWorkshop',
        mood: 'creative',
        time_of_day: 'afternoon',
        distance: 'local',
        importance: 'fun',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 174
      {
        title: 'Attend a Local Poetry Slam',
        description: 'Experience powerful and moving spoken word performances.',
        location: 'indoor',
        cost_category: 'free',
        duration: '2-3 hours',
        activity_type: 'poetrySlam',
        mood: 'creative',
        time_of_day: 'evening',
        distance: 'local',
        importance: 'experience',
        activity_level: 'low',
        image_url: '/api/placeholder/400/300',
      },
      // 175
      {
        title: 'Go on a Guided Wildlife Safari',
        description: 'Observe wildlife in their natural habitat on a guided safari.',
        location: 'outdoor',
        cost_category: 'premium',
        duration: 'Full day',
        activity_type: 'wildlifeSafari',
        mood: 'adventurous',
        time_of_day: 'morning',
        distance: 'far',
        importance: 'experience',
        activity_level: 'high',
        image_url: '/api/placeholder/400/300',
      }
    ];

    for (const idea of sampleDateIdeas) {
      const result = await pool.query(
        `INSERT INTO date_ideas 
        (title, description, location, cost_category, duration, 
        activity_type, mood, time_of_day, distance, importance, 
        activity_level, image_url, is_shared, creator_id) 
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, FALSE, NULL)
        RETURNING id`,
        [
          idea.title,
          idea.description,
          idea.location,
          idea.cost_category,
          idea.duration,
          idea.activity_type,
          idea.mood,
          idea.time_of_day,
          idea.distance,
          idea.importance,
          idea.activity_level,
          idea.image_url,
        ]
      );

      console.log(`✅ Date idea "${idea.title}" added successfully`);
    }

    console.log('✨ Database reset and seeded successfully!');
  } catch (error) {
    console.error('⚠️ Error resetting database:', error);
  } finally {
    await pool.end();
  }
};

resetDatabase();